# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CWGJRequest' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for CWGJRequest
    pod 'AFNetworking'
    pod 'YYModel'
    pod 'EasyMapping'
    pod 'FastEasyMapping'
    pod 'RestKit/ObjectMapping'
end
